# Generated by Django 3.0.5 on 2020-05-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(default=21, max_length=12),
            preserve_default=False,
        ),
    ]
