# Generated by Django 3.0.5 on 2020-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200525_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
