# Generated by Django 3.0.5 on 2020-05-31 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='categoty/default.png', max_length=300, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=150)),
                ('english_name', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('reccomend', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('backgroundcolor', models.CharField(default='F75940', max_length=6)),
                ('image', models.ImageField(default='products/default.png', upload_to='products')),
                ('image_alt', models.CharField(default='image', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='test')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.products_category')),
            ],
        ),
    ]
