# Generated by Django 3.0.5 on 2020-06-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_category',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Product'),
        ),
    ]
