# Generated by Django 3.0.5 on 2020-05-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200503_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='ditail',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
