# Generated by Django 3.0.5 on 2020-06-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_category',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Product'),
        ),
    ]
