# Generated by Django 3.0.5 on 2020-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200605_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_category',
            name='product',
        ),
        migrations.AddField(
            model_name='products_category',
            name='alt',
            field=models.CharField(default='image', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(default='image', max_length=500),
        ),
    ]
