# Generated by Django 3.0.5 on 2020-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200511_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='backgroundcolor',
            field=models.CharField(default='fff', max_length=6),
        ),
    ]
