# Generated by Django 3.0.5 on 2020-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_backgroundcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='backgroundcolor',
            field=models.CharField(default='F75940', max_length=6),
        ),
    ]
