# Generated by Django 3.0.5 on 2020-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200605_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preference',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=128, null=True),
        ),
    ]
