# Generated by Django 3.0.5 on 2020-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200512_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='home/imgs/tabsanj.png', max_length=300, upload_to='home/imgs'),
        ),
    ]
