# Generated by Django 3.0.5 on 2020-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200605_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preference',
            field=models.CharField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third')], max_length=128, null=True),
        ),
    ]
