# Generated by Django 3.0.5 on 2020-05-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_products_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
