# Generated by Django 3.0.5 on 2020-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200512_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='products/default.png', max_length=300, upload_to='products'),
        ),
    ]
