# Generated by Django 3.0.5 on 2020-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200512_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_alt',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
