# Generated by Django 3.0.5 on 2020-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_products_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_category',
            name='image',
            field=models.ImageField(default='categoty/default.png', max_length=300, upload_to='category'),
        ),
    ]
