# Generated by Django 3.0.5 on 2020-05-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_products_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=150)),
                ('english_name', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('reccomend', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('backgroundcolor', models.CharField(default='F75940', max_length=6)),
                ('image', models.ImageField(default='products/default.png', max_length=300, upload_to='products')),
                ('image_alt', models.CharField(default='image', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.products_category')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
